### ISSUE TITLE
A list of missing Textures

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Gregicality/gregicality#568]
Another list to consolidate the list of missing textures. This takes the textures that are still missing from both of the other issues and consolidates them into one spot, and also provides links to the textures if they already exist, but have been forgotten.

- [x] Laser Cooling Unit (done in https://github.com/Gregicality/gregicality/issues/490#issuecomment-860007856)
- [x] Quantum Chromodynamic Charge (Should have a side and top/bottom texture)
- [x] Leptonic Charge (Should have a side and top/bottom texture)
- [x] Charged Lepton Trap Crystal
- [ ] Cryogenic Interface (Three options in https://github.com/Gregicality/gregicality/issues/518#issue-910509579)
- [x] X-Ray Waveguide (Possible textures here: https://github.com/Gregicality/gregicality/issues/518#issuecomment-854488385)
- [x] Fullerene Polymer Matrix Soft Tubing
- [x] Quantumchromodynamic Protecting Plating (Done here: https://github.com/Gregicality/gregicality/issues/490#issuecomment-842806874 There is an alternative texture that might not be done yet)
- [x] Rotating Transparent Surface (Done here https://github.com/Gregicality/gregicality/issues/490#issuecomment-850897398 but needs a mcmeta file)
- [ ] Ballast
- [x] Magnetic Trap (Done here: https://github.com/Gregicality/gregicality/issues/490#issuecomment-849088221)
- [x] Laser Diode (Done here: https://github.com/Gregicality/gregicality/issues/490#issuecomment-849081993)

**Comment by ALongStringOfNumbers** [comment]
After creating this issue, I have opened a PR to add the textures that have existed, but were just forgotten
